# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/nanoc
image: ruby:2.6-alpine

before_script:
  - apk --no-cache add git build-base nodejs py-pygments openssh-client
  - bundle install -j4 --path vendor/bundle

pages:
  stage: build
  script:
  - bundler exec nanoc
  artifacts:
    paths:
    - output

github_pages:
  stage: deploy
  before_script:
    - apk --no-cache add git openssh-client
    - git remote add publish 'git@github.com:nim-by-example/nim-by-example.github.io.git'
    - git config --global user.email 'nim-by-example.github.io'
    - git config --global user.name 'Builder'
    - git config --global push.default simple
    - git checkout master
    - mkdir -p ~/.ssh/
    - echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' > ~/.ssh/known_hosts
    - echo -e "$GIT_CREDENTIALS" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - chmod 0644 ~/.ssh/known_hosts
  script:
    - git add --all .
    - git commit -am'Build Site'
    - git push --force publish
  artifacts:
    paths:
    - output
  only:
  - master
