name: Build and Deploy

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build
        run: bundle exec nanoc && touch output/.nojekyll
        env:
            CI: true
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.ref == 'refs/heads/master'
        with:
          repository-name: nim-by-example/nim-by-example.github.io
          branch: gh-pages
          folder: output
          single-commit: true
          clean: true
          ssh-key: ${{ secrets.DEPLOY_NIM_BY_EXAMPLE_GITHUB_IO }}
